"""initial migration

Revision ID: 2edb4661f46c
Revises: 
Create Date: 2024-12-24 22:28:43.584712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edb4661f46c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['entity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_relationships',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_relationships')
    op.drop_table('entities')
    op.drop_table('entity_types')
    # ### end Alembic commands ###
